In [32]:
# load package
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
# read article
df_all = pd.read_csv('../../input/stage1_unigram.csv', header = 0, names=["id", "article", "words"])
# df_all = pd.read_csv('../../input/stage2_unigram.csv', header = 0, names=["id", "article", "words"])
# df_all = df_all[0:5]
df_all

,id,article,words
0,1001,稻熱病進入好發季節，防檢局籲請農友加強防範 九十三年四月二十一日動植物防疫檢疫局發布之新聞稿...,"['稻熱病', '進入', '好發_季節', '防檢局', '籲請_農友', '加強_防範'..."
1,1004,全民一起來監測紅火蟻 農委會防檢局表示，自3月份起氣溫逐漸回暖，正是紅火蟻開始活躍的季節，也...,"['全民', '監測', '紅火蟻', '農委會', '防檢局_表示', '月份', '氣溫..."
2,1006,"系統測試公告 有關96年1月29日發布之""蔥、蒜紫斑病及薊馬危害日益嚴重，台南農改場籲請農民...","['系統', '測試', '公告', '96', '29', '發布', '蔥', '蒜',..."
3,1008,二期作水稻生育初期，請注意縱捲葉蟲之防治 縱捲葉蟲原本在水稻第一、二期作之孕穗期至齊穗期為害...,"['二期_作', '水稻_生育', '初期', '請', '注意', '縱捲葉蟲', '防治..."
4,1009,請農友加強水稻瘤野螟及白葉枯病防治 農委會防檢局表示，全國各地二期水稻生長陸續進入孕穗期，依...,"['請_農友', '加強', '水稻_瘤野螟', '白葉枯病', '防治', '農委會', ..."
...,...,...,...
416,991,儘速耕除綠肥作物，慎防斜紋夜蛾密度上升 一、依據新聞報導，在新竹、雲林及嘉義等地區因休耕農田...,"['儘速', '耕除', '綠肥作物', '慎防', '斜紋夜蛾_密度', '上升', '依..."
417,993,請農民在「全國滅鼠週」全力配合田間滅鼠工作 請農民在「全國滅鼠週」全力配合田間滅鼠工作行政院...,"['請', '農民', '全國', '滅鼠', '週', '配合', '田間', '滅鼠',..."
418,994,培育健康秧苗，預防水稻徒長病及立枯病發生 培育健康秧苗，預防水稻徒長病及立枯病發生行政院農業...,"['培育', '健康', '秧苗', '預防', '水稻_徒長病', '立枯病', '發生'..."
419,996,水稻進入分蘗盛期請農友加強防範水稻稻熱病 行政院農業委員會動植物防疫檢疫局表示，自本（九十二...,"['水稻', '進入_分蘗', '盛期', '請_農友', '加強_防範', '水稻', '..."
420,999,預防梨木蝨危害，請農友及早實施共同防治 九十三年一月二十八日預防梨木蝨危害，請農友及早實施共...,"['預防', '梨木蝨', '危害', '請_農友', '及早', '實施', '共同_防治..."

In [34]:
# read result file
result_all_df = pd.read_csv('../../output/results_similarity_jac_stage1.csv', header = 0)
result_all_df

        Test  Reference  Similarity  Jaccard_Similarity(%)
0          1         10    0.000000               0.058252
1          1       1000    0.000000               0.045267
2          1       1005    0.000000               0.047826
3          1       1007    0.000000               0.040541
4          1       1010    0.142857               0.043668
...      ...        ...         ...                    ...
313035   998        984    0.000000               0.053488
313036   998        986    0.000000               0.027875
313037   998        988    0.000000               0.024390
313038   998        992    0.333333               0.100000
313039   998        997    0.833333               0.141243

[313040 rows x 4 columns]

In [35]:
# compute tf
vectorizer = CountVectorizer() 
text_count_vector = vectorizer.fit_transform(df_all.words)
tf_vector = text_count_vector.toarray()
tf_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
# compute tf-idf
tfidf_transfomer = TfidfTransformer()
docs_tfidf = tfidf_transfomer.fit_transform(text_count_vector)
tfidf_vector = docs_tfidf.toarray()
tfidf_vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
tf_similarity = cosine_similarity(tf_vector, tf_vector)

# 删除對角線元素(自己對自己)
tf_similarity = tf_similarity[~np.eye(tf_similarity.shape[0],dtype=bool)].reshape(tf_similarity.shape[0],-1)
tf_similarity.flatten()

array([0.11638252, 0.0433555 , 0.16680568, ..., 0.07541641, 0.16477424,
       0.1356777 ])

In [38]:
tfidf_similarity = cosine_similarity(tfidf_vector, tfidf_vector)

# 删除對角線元素(自己對自己)
tfidf_similarity = tfidf_similarity[~np.eye(tfidf_similarity.shape[0],dtype=bool)].reshape(tfidf_similarity.shape[0],-1)
tfidf_similarity.flatten()

array([0.04445818, 0.00442437, 0.04627155, ..., 0.02695592, 0.0599465 ,
       0.0563949 ])

In [39]:
result_df = pd.DataFrame({"TF-CosineSimilarity":tf_similarity.flatten(),
                          "TFIDF-CosineSimilarity":tfidf_similarity.flatten()})
result_df

        TF-CosineSimilarity  TFIDF-CosineSimilarity
0                  0.116383                0.044458
1                  0.043355                0.004424
2                  0.166806                0.046272
3                  0.287453                0.169351
4                  0.156721                0.093073
...                     ...                     ...
176815             0.182012                0.055613
176816             0.111370                0.041898
176817             0.075416                0.026956
176818             0.164774                0.059947
176819             0.135678                0.056395

[176820 rows x 2 columns]

In [22]:
combine_result = pd.concat([result_all_df,result_df], axis=1)
combine_result

,Test,Reference,Similarity,Jaccard_Similarity(%),TF-CosineSimilarity,TFIDF-CosineSimilarity
0,1,10,0.000000,0.058252,0.144837,0.056918
1,1,1000,0.000000,0.045267,0.093737,0.028382
2,1,1005,0.000000,0.047826,0.112383,0.032288
3,1,1007,0.000000,0.040541,0.109976,0.030105
4,1,1010,0.142857,0.043668,0.081238,0.019695
...,...,...,...,...,...,...
313035,998,984,0.000000,0.053488,0.224078,0.046496
313036,998,986,0.000000,0.027875,0.127763,0.023124
313037,998,988,0.000000,0.024390,0.177660,0.033177
313038,998,992,0.333333,0.100000,0.158163,0.098255
313039,998,997,0.833333,0.141243,0.464145,0.251176

In [40]:
combine_result.to_csv("../../output/results_similarity_jac_cos_stage1.csv", index= False)
# result_df.to_csv("../../output/results_cos_stage2.csv", index= False)
# combine_result.to_csv("../../output/results_simi_cosSimi_stage2.csv", index= False)

In [24]:
# End of file